name: BL

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build release
      run: |
        rustup default nightly
        rustup update
        # rustup component add rust-src 
        # cargo ls x86_64-unknown-linux-gnu
        cargo update
        cargo build --release
        cargo lto
        ls -hlR target/**/BL
    - name: Run tests
      run: cargo test --release
