name: BL

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Linux:
    name: Building on Ubuntu. 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build release
      run: |
        # rustup default nightly
        rustup update
        rustup component add rust-src clippy
        # cargo ls x86_64-unknown-linux-gnu
        cargo update
        time cargo build --release
        time cargo lto
        ls -hl target/**/BL
        lscpu
        #lshw
        free -m
    - name: Run tests
      run: cargo test --release
      
  macOS:
    name: Building on macOS. 
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build release
      run: |
        # rustup default nightly
        rustup update
        rustup component add rust-src clippy
        cargo update
        time cargo build --release
        time cargo lto
        ls -hl target/**/BL
        sw_vers
        hostinfo
        sysctl -a | grep brand
    - name: Run tests
      run: cargo test --release
      
  Windows:
    name: Building on Windows. 
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build release
      run: |
        # rustup default nightly
        rustup update
        rustup component add rust-src clippy
        cargo update
        cargo build --release
        cargo lto
        systeminfo
    - name: Run tests
      run: cargo test --release
